### ISSUE TITLE
Sending custom CTAPHID commands 

### ISSUE THREAD

**Issue by szszszsz** [gebogebogebo/ctap-hid-fido2#1]
Hi!

I would like to send a custom CTAPHID command to a FIDO2 device. Is it possible?
As far as I see such functionality is not exposed.

**Comment by gebogebogebo** [comment]
Hi!
What is a custom CTAPHID command?
please tell me in detail.

**Comment by szszszsz** [comment]
Sorry for the delay. Regular CTAPHID commands are e.g. CTAPHID_INIT, CTAPHID_WINK, CTAPHID_PING etc. (see 1). What I would like to have is to send own vendor command on the same lower layer handled by the client software (see 2). In Nitrokey FIDO2 the CTAPHID parsing (3) handles such custom commands (4), like: CTAPHID_GETRNG or CTAPHID_GETVERSION. 

1. https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#usb-commands
2. https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#usb-vendor-specific-commands
3. https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/0afe4ea2e61b69d2f2f672913ee2b4a694997ca6/fido2/ctaphid.c#L607
4. https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/0afe4ea2e61b69d2f2f672913ee2b4a694997ca6/fido2/ctaphid.c#L698

cc @jans23

**Comment by gebogebogebo** [comment]
@szszszsz 

I understand.:smile:
The following custom commands.

```
// Custom commands between 0x40-0x7f
#define CTAPHID_BOOT            (TYPE_INIT | 0x50)
#define CTAPHID_ENTERBOOT       (TYPE_INIT | 0x51)
#define CTAPHID_ENTERSTBOOT     (TYPE_INIT | 0x52)
#define CTAPHID_REBOOT          (TYPE_INIT | 0x53)
#define CTAPHID_GETRNG          (TYPE_INIT | 0x60)
#define CTAPHID_GETVERSION      (TYPE_INIT | 0x61)
#define CTAPHID_LOADKEY         (TYPE_INIT | 0x62)
#define CTAPHID_PROBE           (TYPE_INIT | 0x70)
#define CTAPHID_GETSTATUS       (TYPE_INIT | 0x71)
```

Implementation is possible, but I don't have the Key to test it.

**Comment by szszszsz** [comment]
Great! Regarding the hardware please write to us at `Xupport@nitrokey.com` (replace X with `s`) with your address - we will send a free FIDO2 key to help you with the development tests :-)

Would you be interested later in implementing firmware update commands too? Firmware side these are processed at [bootloader.c#L155](https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/master/targets/stm32l432/bootloader/bootloader.c#L155). These are not CTAPHID commands, but a custom protocol tunneled over Webauthn, so it should be even easier to develop.

**Comment by gebogebogebo** [comment]
@szszszsz 

I sent an e-mail !.

**Comment by gebogebogebo** [comment]
@szszszsz 

Now implement the following commands.
- CTAPHID_GETRNG
- CTAPHID_GETVERSION
- CTAPHID_GETSTATUS

Release soon!

**Comment by szszszsz** [comment]
Hello @gebogebogebo !
I hope you are well! I see by the examples and Readme, that mentioned commands are indeed implemented. Thank you!
For completeness I am linking here the implementation details:
- https://github.com/gebogebogebo/ctap-hid-fido2#nitrokey-custom-commands
- https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/examples/nitro/src/main.rs
- https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/src/nitrokey.rs

**Comment by szszszsz** [comment]
I think we can close this ticket now as done. Let me know in case of any questions!

**Comment by gebogebogebo** [comment]
Thank you!
It was fun!
