### ISSUE TITLE
Support D-Bus

### ISSUE THREAD

**Issue by daxpedda** [gebogebogebo/ctap-hid-fido2#11]
Accessing USB directly isn't desirable on Linux in certain scenarios, like an application running as a Flatpak.
Accessing devices through the D-Bus protocol is an appropriate alternative.
This is the same feature request as here: https://github.com/mozilla/authenticator-rs/pull/146

Is this in the scope of the project? Would PR's be accepted?

**Comment by gebogebogebo** [comment]
@daxpedda

PR is welcome!
However, I don't have Linux in my development environment, 
so testing will be done mainly on Mac, Win, and Raspberry Pi.
