### ISSUE TITLE
NFC support

### ISSUE THREAD

**Issue by daxpedda** [gebogebogebo/ctap-hid-fido2#13]
I know the project is called ctap-**hid**-fido2, but is support for NFC in scope?

I was looking into the details of it, I guess the most straightforward way would be to send APDU messages over the respective NFC APIs of each OS.

Respective API documentations:
- Windows: https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Proximity?view=winrt-20348
- MacOS: https://developer.apple.com/documentation/corenfc
- Linux: https://www.kernel.org/doc/html/latest/networking/nfc.html

Some example implementations:
- Windows: couldn't find any
- MacOS: https://github.com/Yubico/yubikit-ios/tree/master/YubiKit/YubiKit/Connections/NFCConnection
- Linux: https://github.com/Yubico/libfido2/commit/0a1a5ce899a765deb710b30941b02ef890c5cbc3

For Linux it might also be useful to go through a daemon: https://github.com/linux-nfc/neard.

Potentially it might be much simpler to use PCSC to accomplish the task. There is a cross-platform Rust crate too: https://crates.io/crates/pcsc. There is also a PR to do this implementation right here: https://github.com/mozilla/authenticator-rs/pull/114.

**Comment by gebogebogebo** [comment]
@daxpedda 

Thank you very much!
I haven't found a good crate that uses NFC with Rust, but PCSC looks good.
I don't plan to support NFC in this crate, but I would like to consider supporting it in another crate.

I'm working on a library that supports NFC and BLE for Windows, if you're interested.

CTAPcs
https://github.com/gebogebogebo/CTAPcs

**Comment by daxpedda** [comment]
We are actually looking for a Rust implementation, CTAPcs will be a great reference nonetheless.
Feel free to close this issue if it's out of scope.
