### ISSUE TITLE
Yubikey Bio

### ISSUE THREAD

**Issue by obelisk** [gebogebogebo/ctap-hid-fido2#26]
I'm trying to create a resident key (or any key) that requires a fingerprint on the Yubikey bio. Every time I try though, it appears that tapping is enough (using the wrong finger appears to still work).

Is there some setting I need to use to make these keys "bio aware"?

**Comment by obelisk** [comment]
Or is this the method that is used to sign the attestation of the key? Which is separate from the type of key used?

**Comment by gebogebogebo** [comment]
The authenticatorMakeCredential's pubKeyCredParams affects the credentialPublicKey of the Attested credential data.

- [authenticatorMakeCredential's pubKeyCredParams](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#makecred-pubkeycredparams)
- [credentialPublicKey of the Attested credential data](https://www.w3.org/TR/webauthn-2/#credentialpublickey)

The credentialPublicKey in the Attested credential data is Attestation.credential_publickey.

>accomplished by changing the -7 here to -8.

Take a look [here.](https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/src/cose.rs#L50)
It should change to -8.
:smile:
