### ISSUE TITLE
fidokey_pi out of date with fidokey

### ISSUE THREAD

**Issue by obelisk** [gebogebogebo/ctap-hid-fido2#31]
It looks like the fidokey module has been updated but those changes haven't made it into the fidokey_pi module. I'm also unsure why that module is needed.

I've been running this on macOS and it seems to be performing fine, I will get my linux machines out to test it but if it works, I think we can remove that module and the supporting conditionals to check.

What was the original reason behind the fidokey_pi module?

**Comment by gebogebogebo** [comment]
I have not tested on Raspberry Pi and would like to update.
Thank you.

**Comment by gebogebogebo** [comment]
@obelisk 
Hi ,
Version 2.2.2 is released.
Fixed build error on fidokey_pi.
Thank you.
