### ISSUE TITLE
`credential_publickey` DER and PEM now empty

### ISSUE THREAD

**Issue by obelisk** [gebogebogebo/ctap-hid-fido2#36]
I think this change: https://github.com/gebogebogebo/ctap-hid-fido2/commit/3fb2de925df4ae0bdb3570dad91b22f8027762eb#diff-e8afd4d5ffde3d3d24c8c765790dc6bec1108ab9aaf4fd53df8c9a4be0bbe3f7L83

broke having the credential public key data available. I think it's still possible to work around it because it should be in the attestation statement but I just think this parsing is failing or doing something slightly wrong.

I might have some time to look into it over the next few days but maybe it's obvious to @gebogebogebo :)

**Comment by gebogebogebo** [comment]
I know there is a problem with the Attestation public key generated being empty when registered with a key type of Ed25519.

There is an unknown part of the logic for converting COSE format public keys to DERs that has not been implemented.

There is an unknown part of the logic for converting COSE format public keys to DERs that has not been implemented.

If the logic of the following link can be filled in, it can be addressed.
https://github.com/gebogebogebo/ctap-hid-fido2/blob/8310d49cfd0b36de441ab1a6dd4a5477fc29d817/src/cose.rs#L128-L133

If the logic of the following link can be filled in, it can be addressed !

**Comment by obelisk** [comment]
Understood, I can look at it in the coming days :)

In the mean time you can see how I get around the issue and extract the public key from the attestation data here: https://github.com/obelisk/sshcerts/blob/new_fido2/src/fido/parsing.rs#L107-L163

Thanks again for writing this library, I want to help anyway I can!

**Comment by gebogebogebo** [comment]
Thank you as always !!!

**Comment by gebogebogebo** [comment]
Resolved in 3.5.0
