### ISSUE TITLE
How to handle multiple connected devices?

### ISSUE THREAD

**Issue by obelisk** [gebogebogebo/ctap-hid-fido2#38]
I've found that when I have multiple devices connected, the library sometimes selects the wrong one to use. I would like it if, given a key handle, the library would determine automatically what device can fulfill the request but my experience has been that it throws an error if it happens to choose the wrong device.

Is this a mistake I'm making in the way I'm configuring my usage of this code?

**Comment by gebogebogebo** [comment]
Indeed it is. I'll think about it.

**Comment by obelisk** [comment]
I have an idea which I'm going to try and implement and put up in a PR :) Might take me a couple days though

**Comment by obelisk** [comment]
I have two idea, one is pretty simple that I think I can get done today, they other I need some help with.

### Quick solution: List of Devices with Path + New FidoHidKey from path
---
This is pretty simple as all the stuff is basically already there. I just need to implement functions to expose the device paths, and a way to instantiate a device from that path. This will mostly solve my use case but it's not very clean and is not how people expect authenticators to work.

### Long term solution: Select device by tap
---
This is how browsers do it, they wake up all the keys and use the one the user touches. The implementation for this is also pretty straight forward but it needs an implementation of these three C functions: https://github.com/Yubico/libfido2/blob/fa405d8da78e3811e03eed6baff9de1bfcb7e871/src/dev.c#L402-L516

Then we could have a new top level API of `get_device_from_tap`, and then we're set.

**Comment by obelisk** [comment]
@gebogebogebo You're pretty familiar with CTAP :D, how hard do you think it would be to implement that long term solution?

**Comment by gebogebogebo** [comment]
> Quick solution: List of Devices with Path + New FidoHidKey from path
I think this is better to implement in this crate

> Long term solution: Select device by tap
I think this implementation should be implemented in applications that use ctap-hid-fido2. I think this crate is an API and should provide simple functionality.

**Comment by obelisk** [comment]
#41 already implements point one some what, but I still need to refactor the rest of the functions that take `&device` as their first argument to be methods.

I see the selector function which says that it is supported on CTAP 2.1-PRE, but I have a 5Ci and 5C NFC, neither of which it works with (the Yubikey Bio is fine however).

Is it possible I'm using the API incorrectly?

I think there is still room for point two because taking this refactor to completion, the `FidoHidKey` type will be a major interaction point, so there will be `FidoHidKey::new` taking a config and devices you're looking for, and their could be `FidoHidKey::new_from_tap` both of which return a `FidoHidKey`. So I still think it can make sense in this crate.

Thoughts?

**Comment by gebogebogebo** [comment]
The selector function is the authenticatorSelection command, correct?
https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#authenticatorSelection

5Ci and 5C NFC may not implement CTAP 2.1.

If you can get FIDO_2_1_PRE or FIDO_2_1 with get_info(), you can use authenticatorSelection.

```
- versions                           = ["U2F_V2", "FIDO_2_0", "FIDO_2_1_PRE", "FIDO_2_1"]
```

**Comment by obelisk** [comment]
5C and 5Ci both support FIDO_2_1_PRE but it still throws an error on trying to use it.

5C & 5Ci
```
- versions  = ["U2F_V2", "FIDO_2_0", "FIDO_2_1_PRE"]
- ```

**Comment by gebogebogebo** [comment]
FIDO_2_1 support is required to execute ctap_hid_fido2::selection().

https://github.com/gebogebogebo/ctap-hid-fido2/blob/8d7d58b333b9824512b56009dd2ed4e995ef90ea/examples/ctapcli/src/main.rs#L255

**Comment by obelisk** [comment]
I think this comment needs to be updated then: https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/src/lib.rs#L966

I can do that in my PR if you'd like :)

**Comment by gebogebogebo** [comment]
I will correct the comment.
