### ISSUE TITLE
Docs: getting started

### ISSUE THREAD

**Issue by btielen** [gebogebogebo/ctap-hid-fido2#40]
I experimented a bit with your library, thanks for all the work. I tried to run the [register and authenticate example](https://github.com/gebogebogebo/ctap-hid-fido2/blob/511bbc5f64cce744bbbbabaf9bde713f1ed33119/examples/test-with-pin-non-rk/src/main.rs) and encountered two minor problems which could be clarified in the docs.

My environment:
- Ubuntu 20.04
- Yubikey 5 nfc

**Missing libusb-1.0 dependency**

`failed to run custom build command for hidapi v1.3.4` (...) `thread 'main' panicked at 'Unable to find libusb-1.0`

I solved this by installing the `libusb-1.0-0-dev` package by running:
`sudo apt-get install libusb-1.0-0-dev`

**PIN has to be set**

The [register and authenticate example](https://github.com/gebogebogebo/ctap-hid-fido2/blob/511bbc5f64cce744bbbbabaf9bde713f1ed33119/examples/test-with-pin-non-rk/src/main.rs) resulted in two errors, one of which was `0x2B CTAP2_ERR_UNSUPPORTED_OPTION`. This was solved by setting a PIN for my Yubikey with the [Yubikey manager](https://www.yubico.com/support/download/yubikey-manager/).

Hopefully this helps other people to get started.

Edit: fixed links

**Comment by obelisk** [comment]
So I got out some more Yubikeys and tested this myself and got the same behaviour, even when using the APIs that shouldn't require a pin. So I think this is a bug.

Will try and look into it tomorrow but might be a little above my skill level in CTAP :p

**Comment by btielen** [comment]
> It is statically linked, so this error must have occurred at build time and yeah, definitely should be mentioned.

From the `[libusb/hidapi](https://github.com/libusb/hidapi)` (the library that was wrapped around by the rust crate `hidapi`)

> If you want to build your own application that uses HID devices with HIDAPI, you need to get HIDAPI development package.
> 
> Depending on what your development environment is, HIDAPI likely to be provided by your package manager.
> 
> For instance on Ubuntu, HIDAPI is available via APT:
> 
> sudo apt install libhidapi-dev

**Comment by obelisk** [comment]
Yeah, I just thought originally that error occurred when you tried to run the example (which would be a dynamic linking problem) :)

**Comment by gebogebogebo** [comment]
> Missing libusb-1.0 dependency
Thanks for the useful advice!
I will include it in the next version of the documentation.

> PIN has to be set
I did not test with no PIN set.
I will test it.

**Comment by gebogebogebo** [comment]
When PIN is not specified in API such as make_credential_with_args(), the specification is to operate in UV mode (fingerprint authentication).
(This is not a CTAP specification but this crate specification)
Yubikey 5 nfc does not support fingerprint authentication, so CTAP2_ERR_UNSUPPORTED_OPTION.
It is not recommended to use the Authenticator without setting a PIN, so setting a PIN is noted in the documentation.

**Comment by obelisk** [comment]
Is there a way that users of the API could specify that they they would like to override this?

For example, SSH allows you to generate keys from devices that do not have a pin set. Same with websites, let you authenticate with keys which do not require UV.

**Comment by gebogebogebo** [comment]
> SSH allows you to generate keys from devices that do not have a pin set.
Right.

Currently there is no way to override registration or authentication without using a PIN, so we would like to consider this.
