### ISSUE TITLE
Sensitive content handling

### ISSUE THREAD

**Issue by iamihalcea** [gebogebogebo/ctap-hid-fido2#7]
Hi! 👋🏻 

I came across your crate while looking for CTAP implementations and had a look at the code. I noticed an issue with your handling of PINs. For example, you clone the PIN value passed by users:
https://github.com/gebogebogebo/ctap-hid-fido2/blob/44e7b740190d13049740ee710bc0ba9af7a6dbee/src/lib.rs#L333
Handling sensitive material (passwords, keys, PINs) correctly is quite important, including exposing it as little as possible to the rest of the code, and scrubbing the memory away when you're done using it.

I'd be happy to attempt a fix (or to let you address it, of course), but if you think this doesn't fit into your threat model you can obviously ignore this.

**Comment by gebogebogebo** [comment]
@iamihalcea 

Thanks for the advice!
I'd like to modify the code, but would it be better to pass it on by reference instead of cloning it?

` Some(get_pin_token(&device, &cid, pin)?) `

pin -> &str

**Comment by iamihalcea** [comment]
Yes, ideally that's the way, if at all possible (I have to admit that I didn't look at the whole call stack, sorry :( ). If you can simply pass references without copying any of the contents, then that's the best way, as you leave the content handling to the user and then it's up to them to be careful.

Otherwise, I'd suggest copying the content in a [`Secret`](https://docs.rs/secrecy/0.7.0/secrecy/struct.Secret.html) and [exposing it](https://docs.rs/secrecy/0.7.0/secrecy/trait.ExposeSecret.html) whenever you need to. Alternatively (if `Secret` is too restrictive), you should keep track of wherever you copy some of that secret and call [`zeroize`](https://docs.rs/zeroize/1.2.0/zeroize/trait.Zeroize.html#tymethod.zeroize) afterwards. This ensures the memory is cleared.

**Comment by gebogebogebo** [comment]
@iamihalcea 

Thank you for the useful advice!
I'm working on an update to support CTAP 2.1 now, so I'll fix it in that.

**Comment by gebogebogebo** [comment]
updated
