### ISSUE TITLE
CTAP2_ERR_INVALID_OPTION since version 0.3.0

### ISSUE THREAD

**Issue by shimunn** [gebogebogebo/ctap-hid-fido2#73]
Hi,

I've just noticed that all versions starting at 0.3.0 stopped working unless a PIN is set. Each time `0x2C CTAP2_ERR_INVALID_OPTION Not a valid option for current operation.` is returned for `make_credential` and `get_assertion`.

I've already tried to debug the issue however I don't really know where to look since the cbor being sent to the authenticator looks fine to me. If you don't know where to look for the issue either, could you maybe outline what changed since the last major version(commit messages would have been helpful)?

**Comment by gebogebogebo** [comment]
Hi,

Perhaps this may be the effect of this modification.

CTAP2_ERR_UNSUPPORTED_OPTION occurs when make_credential_with_args with an Authenticator with no PIN set #42
https://github.com/gebogebogebo/ctap-hid-fido2/issues/42

Authenticator with no PIN set now causes an error unless without_pin_and_uv() is specified.
https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/examples/test-with-pin-non-rk/main.rs#L314-L365

To distinguish this from the case where a PIN is set 
> enable_info_option(&InfoOption::ClientPin);
to check if the PIN is set.

Please let me know if this is a different problem.

Thanks for pointing that out!

**Comment by shimunn** [comment]
I'm already using `without_pin_and_uv` but with the same result, shouldn't `CTAP2_ERR_UNSUPPORTED_OPTION` indicate that an option that isn't recognised by the authenticator has been set?

**Comment by gebogebogebo** [comment]
I tried resetting the Authenticator in my environment and it worked fine, no `CTAP2_ERR_UNSUPPORTED_OPTION`.
I use Yubikey.
What security key are you using?
the PIN is not set, do you mean immediately after the reset?

**Comment by shimunn** [comment]
> What security key are you using? 

YubiKey 5 NFC and Solokey2

**Comment by gebogebogebo** [comment]
If there is a problem, it may be due to some modification of `make_credential_command.rs`.
I would also like to investigate, but `CTAP2_ERR_UNSUPPORTED_OPTION` does not occur.
Please let me know if there is a detailed way to cause `CTAP2_ERR_UNSUPPORTED_OPTION`.

**Comment by gebogebogebo** [comment]
Could it be that `CTAP2_ERR_UNSUPPORTED_OPTION` is generated by the following operation?
1) device.make_credential_with_args(&make_credential_args)
2) A message appears in Terminal and waits for PIN input.
3) Time out without entering PIN
4) `CTAP2_ERR_UNSUPPORTED_OPTION` occurs

```
----- test-with-pin-non-rk start -----
----- non_discoverable_credentials -----
- Register
- Touch the sensor on the authenticator
Error => response_status err = 0x02 CTAP1_ERR_INVALID_PARAMETER The command included an invalid parameter.
```

I don't understand English very well, so please let me know if I'm wrong.

**Comment by shimunn** [comment]
I've modified `exmaples/reg_auth/main.rs` like [so](https://gist.github.com/shimunn/6a092e736f01d9a3349775b65adc3c32), there is no delay the error appears straight away.

You can't reproduce the issue?

**Comment by gebogebogebo** [comment]
> I've modified exmaples/reg_auth/main.rs like [so](https://gist.github.com/shimunn/6a092e736f01d9a3349775b65adc3c32)

I ran this code, but **it does not reproduce**.
The following log will appear and exit normally

```
Register
- Touch the sensor on the authenticator
- Register Success
Authenticate
- Touch the sensor on the authenticator
- Authenticate Success
```

I am using Yubikey 5.
I have performed a reset and have not set a PIN.

@shimunn 
I'd like to know how to reproduce it.
If you can output logs, etc., please do so.

**Comment by shimunn** [comment]
I think I've found the culprit, `uv` is always set to true despite being set to `None` via the builder:

```
[examples/reg-auth/main.rs:23] &make_credential_args = MakeCredentialArgs {
    rpid: "reg-auth-example-app",
    challenge: [     
        73,                
        70,             
        193,            
        16,         
        203,         
        43,                       
        20,             
        104,            
        47,        
        128,       
        83,         
        25,        
        100,      
        163,        
        184,        
        224,        
        160,         
        122,                 
        131,                      
        166,                       
        254,                   
        223,              
        222,                 
        149,                       
        76,                     
        229,                             
        51,               
        161,          
        237,      
        13,   
        31,    
        30,     
    ],               
    pin: None,           
    key_type: None,     
    uv: None,                              
    exclude_list: [],    
    user_entity: None,  
    rk: None,              
    extensions: None,   
} 
```

```
[src/fidokey/make_credential/make_credential_command.rs:167] params.option_uv = Some(
    true,     
) 
```

I don't have the time to investigate further for today but maybe setting `up = false` and `uv = true` isn't allowed as per spec? Regardless of the spec `uv` shouldn't be set if specified as `false` via the builder.

**Comment by gebogebogebo** [comment]
Reproduced by Yubikey Bio!

I will check the details now, but it may work differently depending on the firmware version of Yubikey.

It may be that `CTAP1_ERR_INVALID_PARAMETER` is being generated by setting `uv=true` even though there is no uv function.
